name: CI

on:
  push:
    branches:
      - "*"

defaults:
  run:
    shell: pwsh

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Install .NET 5.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - name: Build
        run: dotnet build VsValidate.sln --configuration Release

      - name: Run Unit Tests
        run: dotnet test VsValidate.sln --configuration Release --collect:"XPlat Code Coverage" -r CoverageResults

      - name: Check code coverage
        run: .github/workflows/check-code-coverage.ps1 -threshold 100 -resultFolder CoverageResults

      - name: Run integration Tests
        run: .github/workflows/run-integration-tests.ps1 -baseFolder TestCases -exe VsValidate/bin/Release/net5.0/VsValidate.dll

      - name: Upload code coverage
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: CoverageResults/coverage.cobertura.xml