name: CI

on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Install .NET 5.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - name: Build
        run: dotnet build VsValidate.sln --configuration Release

      - name: Run Unit Tests
        run: dotnet test VsValidate.sln --configuration Release --collect:"XPlat Code Coverage"

      - name: Check code coverage
        shell: pwsh
        run: .github/workflows/check-code-coverage.ps1 -threshold 100 -resultFolder VsValidate.Tests/TestResults

      - name: Run integration Tests
        shell: pwsh
        run: .github/workflows/run-integration-tests.ps1 -baseFolder TestCases -exe VsValidate/bin/Release/net5.0/VsValidate.dll

      - name: Setup Java for CodeCoverage results
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Download Coverage reporter
        run: Invoke-WebRequest -Uri 'https://github.com/codacy/codacy-coverage-reporter/releases/download/11.11.0/codacy-coverage-reporter-assembly.jar' -UseBasicParsing -OutFile  ./codacy-test-reporter.jar

      - name: Upload code coverage
        run: .github/workflows/upload-code-coverage.ps1 -token ${{ secrets.CODACY_PROJECT_TOKEN }}
        if: github.head_ref == 0