name: CI

on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Install .NET 5.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - name: Build
        run: dotnet build VsValidate.sln --configuration Release

      - name: Run Unit Tests
        run: dotnet test VsValidate.sln --configuration Release --collect:"XPlat Code Coverage"

      - name: Check code coverage
        shell: pwsh
        run: .github/workflows/check-code-coverage.ps1 -threshold 100 -resultFolder VsValidate.Tests/TestResults
